export const transactions = [
  { id: 1, dttm: "2024-11-01", transaction: "DEBIT", name: "DEBIT PURCHASE -VISA KROGER #0001    111-555-1234AA", memo: null as string | null, amount: -99.91, tag: null as string | null },
];

export const tags = [
  "Banking:Cash",
  "Banking:Fees",
  "Bills:Cable",
  "Bills:Cell Phone",
  "Bills:Credit Card",
  "Bills:Electric",
  "Bills:Garbage",
  "Bills:Gas",
  "Bills:Insurance",
  "Bills:Loan",
  "Bills:Medical",
  "Bills:Water",
  "Income:Paycheck",
  "Service",
  "Service:Bottle Water",
  "Service:Software",
  "Service:Streaming",
  "Shopping",
  "Shopping:Auto",
  "Shopping:Clothing",
  "Shopping:Dining",
  "Shopping:Fuel",
  "Shopping:Grocery",
  "Shopping:Health/Body",
  "Shopping:Pet Care",
  "Shopping:Unknown",
  "Transfer:Kara",
  "Transfer:Saving",
];